### ISSUE TITLE
[landscape workshop] Terraform missing for orchestration

### ISSUE THREAD

**Issue by tequilarista** [cdfoundation/cdf-landscape#73]
key tech should be represented

**Comment by MadsJakobsen** [comment]
Hi @tequilarista, 
I would like to work on this issue😀 I tried to create a PR (Mainly to verify the logo graphics) but manage to get a failing build, so I will head back and see if I missed any info (I marked the PR as a draft for now). I placed It in the pipeline orchestration, is this correct?

**Comment by markyjackson-taulia** [comment]
Thank you @MadsJakobsen 
If you need any help, let me know

**Comment by MadsJakobsen** [comment]
Hey @markyjackson-taulia thanks for following up, I looked at the error from the first submit, I think the issue I had was due to the layout, since it reported the following:

```
Build failed because of:
Page: landscape, section CI & Pipeline Orchestration
Pipeline Orchestration
CDF Graduated
CDF Graduated
CDF Incubating
Continuous Integration
CDF Graduated
CDF Graduated is out of bound
```

However I completely missed the category **Infrastructure Deployments**, I assume this would be a better fit since terraform primary usage is cloud infrastructure deployment and management?

Link to preview: https://github.com/cdfoundation/cdf-landscape/pull/93,  https://deploy-preview-93--cdf-landscape.netlify.app

**Comment by markyjackson-taulia** [comment]
I think so

**Comment by MarckK** [comment]
Closing this as Terraform is [now listed under Infrastructure Deployments](https://github.com/cdfoundation/cdf-landscape/blob/ec9780494f200ad98c0e9fcb6d9ebf1efbb172ad/landscape.yml#L254)

Thanks to everyone who worked on this!
